### ISSUE TITLE
Error when opening Neovim (Error detected while processing FileType Autocommands for "*":)

### ISSUE THREAD

**Issue by hrqmonteiro** [nvim-treesitter/nvim-tree-docs#4] opened 2021-03-11 22:35 UTC
```
Error detected while processing FileType Autocommands for "*":
E5108: Error executing lua ...aqs/start/nvim-tree-docs/lua/nvim-tree-docs/internal.lua:31:
attempt to index local '_local_0_' (a nil value)
```
![2021-03-11_19-34](https://user-images.githubusercontent.com/17055027/110864405-d1baf180-82a0-11eb-8550-175b3facf745.png)

My config is just the plain:

```
require'nvim-treesitter.configs'.setup {
  tree_docs = {
    enable = true,
  },
}
```

**Comment by steelsojka** [comment] 2021-03-12 01:57
This is a duplicate of #3 . Consult the comments in that ticket for a workaround.

**Closed as completed by steelsojka** 2021-03-12 01:57 UTC
Labels: duplicate
